# -------------
# Site settings
# -------------

title: Marianne
description: Site Internet consacré à la langue française et à sa culture
baseurl: "/Marianne"
url: "https://gianlucacosta.info/Marianne/"

facebookPage: "https://www.facebook.com/Marianne-1657508987673092/"


# --------------
# Build settings
# --------------

markdown: kramdown
